name: run-tests

on: [ push, pull_request ]

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: true
            matrix:
                php: [7.2, 7.3, 7.4, 8.0, 8.1]
                laravel: [^6.0, ^7.0, ^8.0, ^9.0]
                dependency-version: [prefer-stable]
                os: [ubuntu-latest]
                exclude:
                    - php: 7.2
                      laravel: ^8.0
                    - php: 7.2
                      laravel: ^9.0
                    - php: 7.3
                      laravel: ^9.0
                    - php: 7.4
                      laravel: ^9.0
                    - php: 8.1
                      laravel: ^6.0
                    - php: 8.1
                      laravel: ^7.0

        name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }} - OS ${{ matrix.os }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, soap, intl, gd, exif, iconv
                  coverage: none

            - name: Install dependencies
              run: |
                  composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

            - name: Execute tests
              run: vendor/bin/phpunit
